baseURL = "/"
title = "openGauss documentation"

disablePathToLower = true

# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
uglyURLs = true
buildFuture = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# Define the number of posts per page
paginate = 10


[languages]

[languages.en]
    languageCode = "en"
    contentDir = "content/en"

[languages.zh]
    languageCode = "zh"
    contentDir = "content/zh"


[params]
    defaultKeywords = ["devows", "hugo", "go", "openGauss"]
    author = "Site template made by devcows Modified by openGauss team"
    defaultDescription = "Select the version and chapter of the openGauss documentation you want to view."
    email = "contact@opengauss.org"

    ### DOC Configurations
    BookRepo = 'https://gitee.com/opengauss/docs/blob'
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true
    BookMenuBundleActiveLinkColor = '\#004ed0'

    languageZh = "中文"
    languageEn = "English"


    notFound = "404"

